VEN-35 Go to home URL when switching stores
spree/spree_backend pull request #77
Opened 2021-12-15 13:22 UTC by aleksandarpetrushev

2021-12-15 13:40 UTC, aleksandarpetrushev commented
@damianlegawiec So from the failing specs I can see that we want to be redirected to the same path (example /products) when we switch stores. Do I fix the specs and continue with this approach or do I go for another approach to fix this?

2021-12-15 14:18 UTC, damianlegawiec requested changes

2021-12-15 14:18 UTC, damianlegawiec commented on app/helpers/spree/admin/stores_helper.rb
> +        link_to icon + store.unique_name, URI.join(url_for(host: store.formatted_url), '/admin').to_s,
```suggestion
        link_to icon + store.unique_name, spree.admin_url(domain: store.formatted_url),
```

2021-12-19 22:20 UTC, damianlegawiec approved these changes

2021-12-19 23:00 UTC, merged